[Feat] 새 친구 등록 / 친구 프로필 수정 페이지 구현
Favor-Gift-Reminder/Favor-iOS pull request #130
Opened 2023-05-20 05:34 UTC by eung7

## ⚠️ 이슈 번호

> 브랜치에 할당된 이슈 번호

## ✌️ 구현/추가 사항

https://github.com/Favor-Gift-Reminder/Favor-iOS/assets/97531269/143366bc-8ea5-4df7-a853-42bbf7be03bb

- FavorProfileImageView 구현
- FriendManagement UI 구현

## 💬 코멘트

사실 여기서 적용할 것이 더 많은데, 예를 들어서 사진 추가 버튼을 누르면 
`ImagePicker`가 나온다던가, 
프로필 수정은 아직 그 전 페이지가 개발이 안 되어서 보류 상태야

그래서 일단 이 페이지는 작업을 여기까지 남겨두고 
급한 바텀시트로 넘어가는게 어떨까 싶어 !

2023-05-20 06:32 UTC, nomatterjun commented
`FavorProfileImageView` 변경점 적용해서 넘기면 좋을 것 같아!

![profile](https://github.com/Favor-Gift-Reminder/Favor-iOS/assets/60438045/3caa2f78-1bda-4ce1-b29d-3fcc7165068c)

아래 플러스 버튼이 변경됐대

2023-05-20 07:11 UTC, nomatterjun requested changes

2023-05-20 07:11 UTC, nomatterjun commented on Favor/FavorKit/Sources/FavorKit/Base/BaseFriendCell.swift
> +      make.leading.equalToSuperview().inset(20.0)
이거 내가 구현한 화면들에서는
`UICollectionView` 자체에 Inset을 줘서 얘 자체에 `inset`을 주면 레이아웃이 망가지거든..
그래서 `BaseFriendCell`이 아니라 나처럼 `UICollectionView` 자체를 줄이거나 `NSCollectionLayoutItem/Group/Section`에서 적용해줘야 할 것 같아..!

2023-05-21 07:50 UTC, eung7 commented on Favor/FavorKit/Sources/FavorKit/Base/BaseFriendCell.swift
> +      make.leading.equalToSuperview().inset(20.0)
그러니까 형 말은
`CollectionView` 자체의 `leading`과 `trailing`의 값을 `20`을 주고
그 안에 들어있는 헤더나 셀의 마진 값은 없도록 주는게 낫다는 거지 ?!

2023-05-21 07:54 UTC, eung7 commented on Favor/FavorKit/Sources/FavorKit/Base/BaseFriendCell.swift
> +      make.leading.equalToSuperview().inset(20.0)
그런데 `CollectionView` 자체에 마진 값을 줘버리면
`scrollIndicator` 같은 게 부자연스러울 수 있을 것 같은데,
그 부분은 어떻게 되는걸까 ? ..
아예 숨김 처리로?

2023-05-21 07:54 UTC, eung7 commented
![스크린샷 2023-05-21 16 41 11](https://github.com/Favor-Gift-Reminder/Favor-iOS/assets/97531269/9d169780-d975-42aa-8b79-8b1a5b4a8c55)

수정된 디자인으로 적용 했어 !

2023-05-21 07:54 UTC, nomatterjun commented on Favor/FavorKit/Sources/FavorKit/Base/BaseFriendCell.swift
> +      make.leading.equalToSuperview().inset(20.0)
응 맞아 `CollectionView`자체의 `contentInsets(`UIEdgeInsets`)를 줘도 되고
`Item`, `Group`, `Section`의 `contentInsets(NSDirectionalEdgeInsets`) 프로퍼티를 건드려도 되고!

2023-05-21 08:04 UTC, nomatterjun commented on Favor/FavorKit/Sources/FavorKit/Base/BaseFriendCell.swift
> +      make.leading.equalToSuperview().inset(20.0)
> 그런데 `CollectionView` 자체에 마진 값을 줘버리면 `scrollIndicator` 같은 게 부자연스러울 수 있을 것 같은데, 그 부분은 어떻게 되는걸까 ? .. 아예 숨김 처리로?

응 나는 다 숨김 처리 했어
스크롤바가 우리 앱에 어울리는 것 같지가 않더라고..

2023-05-21 08:04 UTC, nomatterjun commented on Favor/FavorKit/Sources/FavorKit/Base/BaseFriendCell.swift
> +      make.leading.equalToSuperview().inset(20.0)
스크롤을 살리고 싶을 때는 `CompositionalLayout`에서 inset을 주면 될 듯..!

2023-05-21 08:21 UTC, nomatterjun approved these changes

2023-05-21 08:21 UTC, nomatterjun commented
👍👍👍

2023-05-21 08:21 UTC, eung7 commented on Favor/FavorKit/Sources/FavorKit/Base/BaseFriendCell.swift
> +      make.leading.equalToSuperview().inset(20.0)
수정완료 ~!

2023-05-21 08:38 UTC, merged