[Fix] 기념일 목록 분기처리
Favor-Gift-Reminder/Favor-iOS pull request #157
Opened 2023-06-16 17:47 UTC by eung7

## ⚠️ 이슈 번호

> #155 

## ✌️ 구현/추가 사항

https://github.com/Favor-Gift-Reminder/Favor-iOS/assets/97531269/adc806fa-c534-46a3-bcd1-1e370025b6d2

- 기념일 정렬 기준 변경
- `AnniversaryList VC/Reactor` 분기처리 및 UI변경 (`AnniversaryListType`)
  - `FloatyButton` 및 `EditButton`, `navigationBarTitle`
- `FriendPageViewReactor`에 친구 조회 Fetcher 추가
- 그 외 FriendPage 로직 수정 

## 💬 코멘트

> 시험이 이번주에 끝나가지고 프로젝트 키는 게 너무 오랜만이였네 ㅠㅠ.. 적응좀 하느라 좀 스피드가 더뎠던 것 같아
일단 디테일하게 더 손볼 게 있을 것 같긴한데, 일단 이 브랜치는 여기서 마무리하고 
다른 급한 UI작업으로 넘어가는 게 좋을 것 같아!

2023-06-16 21:23 UTC, nomatterjun requested changes

2023-06-16 21:23 UTC, nomatterjun commented on Favor/Favor.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +        "version" : "13.8.0"
이전 버전에서 iOS 17.0이랑 Realm이랑 호환성 이슈가 하나 있어서 패키지 업데이트 한 번 부탁해..!

2023-06-16 21:23 UTC, nomatterjun commented on Favor/Favor/Sources/Scenes/AnniversaryList/Reactors/AnniversaryListViewReactor.swift
> +  let anniversaryListType: AnniversaryListType
이 `anniversaryListType` 이라는 프로퍼티를 `State`가 아니라 일반 프로퍼티로 뺀 이유가 있을까?
`State`에 넣고 다른 프로퍼티들과 마찬가지로 VC 쪽에서 구독해서 사용하면 VC 생성자로 주입시키지 않아도 될 것 같아

2023-06-16 21:23 UTC, nomatterjun commented on Favor/Favor/Sources/Scenes/AnniversaryList/Reactors/AnniversaryListViewReactor.swift
> +          .flatMap { (status, friend) -> Observable<Mutation> in
지금 안쓰이는 변수는 `_` 처리 부탁해..!
```suggestion
          .flatMap { (_, friend) -> Observable<Mutation> in
```

2023-06-16 21:23 UTC, nomatterjun commented on Favor/Favor/Sources/Scenes/AnniversaryList/Reactors/AnniversaryListViewReactor.swift
> +  init(anniversaryListType: AnniversaryListType) {
생성자 파라미터명이 너무 긴 것 같아..!

어차피 앞에 `AnniversaryListViewReactor`라고 "AnniversaryList"라는 정보가 주어지니까
`init(_ viewType: AnniversaryListType)`이나 `init(_ type: AnniversaryListType`처럼 축소해도 될 것 같아.

2023-06-16 21:23 UTC, nomatterjun commented on Favor/Favor/Sources/Scenes/AnniversaryList/Reactors/AnniversaryListViewReactor.swift
> +            return .just(.updateAnniversaries(friend.anniversaryList.sort()))
밑의 `transform`에서 공통적으로 `sort` 처리 되는 것 같아서 여기서는 정렬 처리 없이 넘겨도 될 듯..?
```suggestion
            return .just(.updateAnniversaries(friend.anniversaryList))
```

2023-06-16 21:23 UTC, nomatterjun commented on Favor/Favor/Sources/Scenes/Profile/FriendPage/Reactors/FriendPageViewReactor.swift
> +            .just(.setFriend(friend))
이 부분 이제 `Friend` 타입에 대해서 자유롭게 접근 가능하니까
`Friend` 타입의 프로퍼티를 `State`에 추가해주고
하나의 `updateFriend` `mutation`으로 처리해주는게 좋을 것 같아!

아마 내가 작업한 곳들도 지금 여기처럼 분리해서 작업되어 있을 것 같은데
나도 차차 바꿔주도록 할게..

2023-06-17 09:32 UTC, eung7 commented on Favor/Favor/Sources/Scenes/AnniversaryList/Reactors/AnniversaryListViewReactor.swift
> +  let anniversaryListType: AnniversaryListType
나도 이 생각을 해봤는데,
`bind(reactor:)`에서 구독해서 사용하면 당연히 작동하긴 하는데
구독되는 시점이 조금 느려서 `Push`가 되고 옆으로 넘어가는 과정 중에서 UI가 변경되어서
너무 어색하게 바뀌는 이슈가 있어..

어떻게 생각해? 아니면 다른 좋은 방법이 있을까?

2023-06-17 10:28 UTC, nomatterjun commented on Favor/Favor/Sources/Scenes/AnniversaryList/Reactors/AnniversaryListViewReactor.swift
> +  let anniversaryListType: AnniversaryListType
혹시 `viewDidLoad`에서 세팅해줘도 그런거야??
그렇게까지 느릴 이유는 딱히 없는 것 같은데.. 🤔..

2023-06-17 10:35 UTC, eung7 commented on Favor/Favor/Sources/Scenes/AnniversaryList/Reactors/AnniversaryListViewReactor.swift
> +  let anniversaryListType: AnniversaryListType
아 `viewDidLoad`에서 사용할 생각을 못 했네 😅
그러면 당연히 할 수 있을 것 같아 !!

2023-06-17 10:37 UTC, nomatterjun commented on Favor/Favor/Sources/Scenes/AnniversaryList/Reactors/AnniversaryListViewReactor.swift
> +  let anniversaryListType: AnniversaryListType
아하..! 그럼 해보고 결과 알려줘..! 👍

2023-06-17 10:39 UTC, eung7 commented
요청 사항 모두 반영했어 ! 
<img width="571" alt="image" src="https://github.com/Favor-Gift-Reminder/Favor-iOS/assets/97531269/023a4117-f2c0-4222-9e1e-767382b061b6">

형 말대로 State에 Friend를 참조하게 했어
그리고 items이외의 섹션들은 모두 직접적으로 필요없을 것 같아서 모두 지워줬어.

한번 확인해주고 다른 요청사항 있으면 다시 코멘트 남겨줘 !

2023-06-17 11:20 UTC, nomatterjun requested changes

2023-06-17 11:20 UTC, nomatterjun commented on Favor/Favor/Sources/Scenes/AnniversaryList/Reactors/AnniversaryListViewReactor.swift
> +  let anniversaryListType: AnniversaryListType
생성자에서  `initialState`로 값을 넣어주고 시작하니까
이 프로퍼티는 지워줘도 될 것 같아..!

2023-06-17 11:20 UTC, nomatterjun commented on Favor/Favor/Sources/Scenes/AnniversaryList/Reactors/AnniversaryListViewReactor.swift
> +      switch self.anniversaryListType {
```suggestion
      switch self.currentState.anniversaryListType {
```

2023-06-17 11:27 UTC, eung7 commented
급하게 고치느라 정신이 없었네 .. 😅
반영됐어 !

2023-06-17 11:27 UTC, nomatterjun commented
굿!! 고생했어 👍👍👍

2023-06-17 11:28 UTC, nomatterjun approved these changes

2023-06-17 11:41 UTC, merged