[Feat] FavorTabBar 구현
Favor-Gift-Reminder/Favor-iOS pull request #160
Opened 2023-06-21 06:11 UTC by eung7

## ⚠️ 이슈 번호

> #158 

## ✌️ 구현/추가 사항

https://github.com/Favor-Gift-Reminder/Favor-iOS/assets/97531269/d71f48ed-d9f9-4f2c-b4e1-525aaee0e23d

![image](https://github.com/Favor-Gift-Reminder/Favor-iOS/assets/97531269/8ae4a9ed-0614-4883-a2bd-3e18b3fecbeb)

> 일단 아래는 그냥 보면 생소할 수도 있는 부분을 부가적으로 설명을 써놓을게 ! 

### BezierPath를 이용

사실 처음에 어떻게 구현해야하는지 막막했는데
그냥 이미지로 퉁 치자니, 기기마다 사이즈가 잘 나올지 우려가 됐었고
결국에는 그냥 한땀한땀 그리는 게 정답이었던 것 같아서 `BezierPath`를 이용해서 테두리를 그렸어!
아래 메서드가 주요 레이러를 그리는 메서드인데 
주석을 달아놨으니까 한번 확인해줘 ! 

```swift
  /// 테두리 레이어를 그리는 메서드입니다.
  private func drawPath() -> CGPath {
    /// 전체 너비 값의 중간 값입니다.
    let centerWidth: CGFloat = self.frame.width / 2
    /// 모서리에 `CornerRadius`값 입니다.
    let borderCornerRadius: CGFloat = 12.0
    /// 중앙의 커브가 시작 지점부터 끝 지점까지의 너비 값입니다.
    let circleCurveWidth: CGFloat = 64.0
    /// 첫 번쨰 커브가 시작되는 좌표입니다.
    let startCurvePoint = CGPoint(x: centerWidth - (circleCurveWidth / 2), y: 0)
    /// 반원이 시작되는 좌표입니다.
    let startSemiCirclePoint = CGPoint(x: startCurvePoint.x + 8, y: 7)
    /// 반원의 중간 부분의 좌표입니다.
    let middleSemiCirclePoint = CGPoint(x: centerWidth, y: 25)
    /// 반원의 끝 부분의 좌표입니다.
    let endSemiCirclePoint = CGPoint(x: centerWidth + (circleCurveWidth / 2) - 8, y: 7)
    /// 마지막으로 최종 커브가 종료되는 좌표입니다.
    let endCurvePoint = CGPoint(x: centerWidth + (circleCurveWidth / 2), y: 0)
    /// 오른쪽 상단의 모서리 좌표입니다.
    let topRightPoint = CGPoint(x: self.frame.maxX, y: 0)
    /// 오른쪽 하단의 모서리 좌표입니다.
    let bottomRightPoint = CGPoint(x: self.frame.maxX, y: self.frame.maxY)
    /// 왼쪽 하단의 모서리 좌표입니다.
    let bottomLeftPoint = CGPoint(x: 0, y: self.frame.maxY)
        
    // 1. 선을 그리기 시작합니다.
    let bezPath = UIBezierPath()
    bezPath.move(to: CGPoint(x: borderCornerRadius, y: 0))
    bezPath.addLine(to: CGPoint(x: centerWidth - (circleCurveWidth / 2), y: 0))
    // 2. 첫 번째 커브가 시작되는 구간입니다.
    bezPath.addCurve(
      to: startSemiCirclePoint,
      controlPoint1: CGPoint(x: startCurvePoint.x + 5, y: 0),
      controlPoint2: CGPoint(x: startSemiCirclePoint.x - 0.7, y: 4.8)
    )
    // 3. 반원이 시작되는 구간입니다. 반원의 중간 지점에서 종료됩니다.
    bezPath.addCurve(
      to: middleSemiCirclePoint,
      controlPoint1: CGPoint(x: startSemiCirclePoint.x + 3, y: startSemiCirclePoint.y + 10),
      controlPoint2: CGPoint(x: middleSemiCirclePoint.x - 12, y: middleSemiCirclePoint.y)
    )
    // 4. 반원이 중간 지점부터 끝 부분까지 반원을 그립니다.
    bezPath.addCurve(
      to: endSemiCirclePoint,
      controlPoint1: CGPoint(x: middleSemiCirclePoint.x + 12, y: middleSemiCirclePoint.y),
      controlPoint2: CGPoint(x: endSemiCirclePoint.x - 3, y: endSemiCirclePoint.y + 10)
    )
    // 5. 반원의 끝 부분부터 커브가 종료되는 좌표까지 커브를 그립니다.
    bezPath.addCurve(
      to: endCurvePoint,
      controlPoint1: CGPoint(x: endSemiCirclePoint.x + 0.7, y: 4.8),
      controlPoint2: CGPoint(x: endCurvePoint.x - 5, y: 0)
    )
    // 6. 나머지 선분과 테두리의 CornerRadius를 적용한 모서리를 그립니다.
    bezPath.addLine(to: CGPoint(x: self.frame.maxX - borderCornerRadius, y: 0))
    bezPath.addCurve(
      to: CGPoint(x: topRightPoint.x, y: borderCornerRadius),
      controlPoint1: CGPoint(x: topRightPoint.x - borderCornerRadius + 6.63, y: 0),
      controlPoint2: CGPoint(x: topRightPoint.x, y: 5.37)
    )
    bezPath.addLine(to: bottomRightPoint)
    bezPath.addLine(to: bottomLeftPoint)
    bezPath.addLine(to: CGPoint(x: 0, y: borderCornerRadius))
    bezPath.addCurve(
      to: CGPoint(x: borderCornerRadius, y: 0),
      controlPoint1: CGPoint(x: 0, y: 5.37),
      controlPoint2: CGPoint(x: 5.37, y: 0)
    )
    bezPath.close()
    
    return bezPath.cgPath
  }
```

### 중앙 추가 버튼

사실 이것도 고민이 많았는데
처음에는 `MiddleButton`을 `FavorTabBarController`에서 레이아웃을 추가하고 관리해주자! 라고 생각했는데,
문제가 됐었던 것은 `hidesBottomBarWhenPushed`가 `true`가 될 때, 
1. `tabBar`가 Hidden되면서 제약조건이 변경이 되나봐.. 그래서 `MiddleButton`의 위치도 바뀜
2. 애초에 `hidesBottomBarWhenPushed`가 되는 타이밍을 알아야하는데, 오버라이드의 옵저버를 구현해도 값이 관찰되지 않음

이 두 가지의 문제점이 있어서 `FavorTabBar`에서 레이아웃을 잡았어 !

그래서 `FavorTabBar`에서 `MiddleButton`을 관리하게 됐어
`FavorTabBar` 같은 경우 왼쪽 상단 `CornerRadius`가 들어간 부분이 `CGPoint`가 (0,0)인데,
그래서 버튼의 가운데를 기준으로 위쪽은 터치가 안 되는 문제가 발생했어..
이에 대한 해결 방법이 `hitTest`를 오버라이드해서 피타고라스 법칙을 이용한 방법인데
터치한 영역을 버튼의 `Center`를 기준으로해서 반지름인 20 이하이면 버튼이 클릭이 되는 방법으로 구현했어!

```swift
  /// 터치 영역을 조절하는 메서드입니다.
  override func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {
    if self.isHidden {
      return super.hitTest(point, with: event)
    }
    let from = point
    let to = self.middleButton.center
    
    // 피타고라스 법칙을 이용하여 중앙 버튼의 터치를 감지합니다.
    return sqrt((from.x - to.x) * (from.x - to.x) + (from.y - to.y) * (from.y - to.y))
    <= 20 ? self.middleButton :super.hitTest(point, with: event)
  }
```

## 💬 코멘트

> 고쳐야할 부분이나 개선해야할 부분이 있다면 코멘트 달아줘 ~!

2023-06-21 16:21 UTC, nomatterjun requested changes

2023-06-21 16:21 UTC, nomatterjun commented on Favor/Favor/Sources/Scenes/Dashboard/Views/FavorTabBar.swift
> +    <= 20 ? self.middleButton :super.hitTest(point, with: event)
```suggestion
    <= 20 ? self.middleButton : super.hitTest(point, with: event)
```

아이디어 굿! 👍
사소한거 하나만 수정 부탁해!

2023-06-21 16:21 UTC, nomatterjun commented on Favor/Favor/Sources/Scenes/Dashboard/Views/FavorTabBar.swift
> +    }
```suggestion
    self.homeButton.isSelected = self.selectedIndex == 0
    self.friendButton.isSelected = self.selectedIndex == 1
```

한 번에 설정해주면 좋을 듯..!

2023-06-21 16:21 UTC, nomatterjun commented on Favor/Favor/Sources/Scenes/Dashboard/Views/FavorTabBar.swift
> +    button.setImage(.favorIcon(.largeNewGift), for: .normal)
<img src="https://github.com/Favor-Gift-Reminder/Favor-iOS/assets/60438045/68b13bbb-a598-4cbf-877e-92c767246aae" width="300">

이거 혹시 통째로 이미지가 아니라 배경색상 주고 가운데 + 이미지만 넣는걸로 적용해줄 수 있을까??

그리고 왜 그런지 모르겠는데 내 시뮬에서는 이미지 자체가 안뜨네..
에셋에는 추가되어 있는데..

2023-06-21 16:21 UTC, nomatterjun commented on Favor/Favor/Sources/Scenes/Dashboard/Views/FavorTabBar.swift
> +    shapeLayer.shadowOpacity = 0.03
이거 내가 어딘가에서 ShadowPath로 구현하는게 씨피유 소모량이 더 적다고 들어서
그거 사용해서 구현해주면 좋을 것 같아!

사실 얼마나 더 좋은지는 측정해보지 않았지만..

2023-06-21 16:21 UTC, nomatterjun commented on Favor/Favor/Sources/Scenes/Dashboard/Views/FavorTabBar.swift
> +    }
```suggestion
    self.homeButton.snp.makeConstraints { make in
      make.top.equalToSuperview().inset(12.0)
      make.centerX.equalToSuperview().multipliedBy(0.5)
    }
    
    self.friendButton.snp.makeConstraints { make in
      make.top.equalToSuperview().inset(12.0)
      make.centerX.equalToSuperview().multipliedBy(1.5)
    }
```

좌측 우측을 기준으로 레이아웃을 잡으면 화면이 작아지거나 커질 때 한 쪽으로 쏠릴 수 있을 것 같아
`centerX`를 기준으로 정렬해주는게 좋을듯..!

2023-06-22 03:04 UTC, eung7 commented on Favor/Favor/Sources/Scenes/Dashboard/Views/FavorTabBar.swift
> +    button.setImage(.favorIcon(.largeNewGift), for: .normal)
또 에셋 버그구나.. 

이게 내가 자체로 에셋으로 추가한 이유가

![image](https://github.com/Favor-Gift-Reminder/Favor-iOS/assets/97531269/b5678abe-ad56-4463-bbe0-c8dd62d7604b)

이런식으로 겉에는 채워져있고 +인 부분은 투명으로 되어있어서
투명인 부분때문에 마스킹을 해줘야해서 그랬던 것 같아..
그리고 사이즈를 적절하게 설정하면 바깥의 원도 커지기 때문에 
결국 마스킹이 이중으로 들어가야하는 번거로움이 생겨 ㅠㅠ 

그래서 이건 가희한테 따로 배경없이 따로 +부분만 아이콘 Export 할 수 있게 요청할게 ! 

또 다른 좋은 방법이 있으면 알려줘 !

2023-06-22 03:15 UTC, eung7 commented on Favor/Favor/Sources/Scenes/Dashboard/Views/FavorTabBar.swift
> +    shapeLayer.shadowOpacity = 0.03
```swift
    // Shadow
    shapeLayer.shadowColor = UIColor.favorColor(.black).cgColor
    shapeLayer.shadowOffset = CGSize(width: 0, height: -1)
    shapeLayer.shadowOpacity = 0.03
    shapeLayer.shadowPath = UIBezierPath(rect: shapeLayer.bounds).cgPath
```

혹시 이렇게 구현한 게 형 의도에 맞을까..?

2023-06-22 04:21 UTC, nomatterjun commented on Favor/Favor/Sources/Scenes/Dashboard/Views/FavorTabBar.swift
> +    button.setImage(.favorIcon(.largeNewGift), for: .normal)
아니면 얘도 BezierPath 써서 직접 그리면 되긴 할 듯...

2023-06-22 04:35 UTC, nomatterjun commented on Favor/Favor/Sources/Scenes/Dashboard/Views/FavorTabBar.swift
> +    shapeLayer.shadowOpacity = 0.03
맞아! 페이버에도 선물 공유 화면쪽에 사용하고 있어

2023-06-22 04:56 UTC, nomatterjun commented
왜 내가 건들면 액션이 망가지는 것이야.. 😡
에러 메시지도 없이 돌릴 때마다 건들지도 않은 엉뚱한 다른 곳에서 에러가 나는걸 보니까 XCode 베타랑 뭐가 안맞는건가..? 라는 생각까지 드네..
응철이 너가 푸쉬한건 잘 돌아가나 확인해보고 좀 더 살펴볼게...

2023-06-22 05:22 UTC, eung7 commented on Favor/Favor/Sources/Scenes/Dashboard/Views/FavorTabBar.swift
> +    button.setImage(.favorIcon(.largeNewGift), for: .normal)
이건 아이콘 따로 달라고 부탁해볼게 !

2023-06-22 11:38 UTC, eung7 commented
ㅠㅠ 왜 안 되는거지?
일단 이 브랜치는 남겨두고 다른 작업 하고 있으면 될까?

2023-06-22 11:40 UTC, nomatterjun commented
음.. 아무거나 커밋해서 푸쉬 한 번 날려줄 수 있을까??

2023-06-22 11:54 UTC, EnnzoKim commented
커밋 했어 !

2023-06-22 11:58 UTC, eung7 commented
또 안 되네.. 혹시 에셋문제일까..?

2023-06-22 12:01 UTC, nomatterjun commented
일단 액션 성공했던 [a17e6b4](https://github.com/Favor-Gift-Reminder/Favor-iOS/pull/160/commits/a17e6b48ee613a9f0be76b20439e78e0d602993a) 시점으로 돌려볼게

2023-06-22 12:07 UTC, nomatterjun commented
흠... 🤔

2023-06-22 12:41 UTC, nomatterjun commented
이거 왜 이러는지 알 수가 없네...
일단 로컬에서는 빌드 정상적으로 잘 되니까 강제로 머지해도 될 것 같아..

2023-06-22 12:42 UTC, nomatterjun approved these changes

2023-06-22 13:33 UTC, eung7 commented
오케이! 중앙 버튼 관련해서 만들고 강제 머지 할게 ~!

2023-06-23 00:29 UTC, eung7 commented
형 혹시 이 브랜치 `ic_tabbar`라는 에셋 추가했는데
혹시라도 또 안 뜨면
형이 수동으로 추가해줄 수 있을까? 
아래 이미지는 피그마 디자인시스템에 있어! 

![ic_tabbar](https://github.com/Favor-Gift-Reminder/Favor-iOS/assets/97531269/75459f16-7d1c-422b-bb43-6cc000d9030e)

2023-06-23 03:52 UTC, nomatterjun commented
이번에는 제대로 나오고 있어! 👍

2023-06-23 07:30 UTC, merged